'use strict',
    module.exports = {
        AbstractLogicSpecification: require('./abstract-logic-specification'),
        AbstractSpecification: require('./abstract-specification'),
        AllOfSpecification: require('./all-of-specification'),
        AnyOfSpecification: require('./any-of-specification'),
        IsEqualSpecification: require('./is-equal-specification'),
        IsGreaterThanOrEqualSpecification: require('./is-greater-than-or-equal-specification'),
        IsGreaterThanSpecification: require('./is-greater-than-specification'),
        IsIncludedSpecification: require('./is-included-specification'),
        IsLessThanOrEqualSpecification: require('./is-less-than-or-equal-specification'),
        IsLessThanSpecification: require('./is-less-than-specification'),
        IsNotEqualSpecification: require('./is-not-equal-specification'),
        IsNotIncludedSpecification: require('./is-not-included-specification'),
        IsNotNullSpecification: require('./is-not-null-specification'),
        IsNotPresentSpecification: require('./is-not-present-specification'),
        IsNotTrueSpecification: require('./is-not-true-specification'),
        IsNullSpecification: require('./is-null-specification'),
        IsPresentSpecification: require('./is-present-specification'),
        IsTrueSpecification: require('./is-true-specification')
    };
